### ISSUE TITLE
module searching terminates unexpectedly at certain directory

### ISSUE THREAD

**Issue by shankerwangmiao** [BYVoid/continuation#31]
suppose the source tree is 

	/path/to/root
			 |
	         +--sub
			 |  |
		     |  +--main.js
		     |
		     +--node_modules
		        |
		        +--aaa
		           |
		           +--index.js

and `main.js` is 

	require('aaa');
	console.log('sub/main.js');

while `index.js` is

	console.log("this is aaa");
	
and below is the issue

	% pwd
	/path/to/root
	% continuation sub/main.js
	module.js:340
	    throw err;
	          ^
	Error: Cannot find module 'aaa'
	  at Function.Module._resolveFilename (module.js:338:15)
	  at Function.Module._load (module.js:280:25)
	  at Module.require (module.js:364:17)
	  at require (module.js:380:17)
	  at Object.<anonymous> (sub/main.js:1:69)
	  at Module._compile (module.js:456:26)
	  at executeTopModule (/usr/local/lib/node_modules/continuation/lib/cli.js:131:14)
	  at Object.exports.main (/usr/local/lib/node_modules/continuation/lib/cli.js:86:7)
	  at Object.<anonymous> (/usr/local/lib/node_modules/continuation/bin/continuation:3:5)
	  at Module._compile (module.js:456:26)
	  at Object.Module._extensions..js (module.js:474:10)
	  at Module.load (module.js:356:32)
	  at Function.Module._load (module.js:312:12)
	  at Function.Module.runMain (module.js:497:10)
	  at startup (node.js:119:16)
	  at node.js:906:3
	% continuation ./sub/main.js
	this is aaa
	sub/main.js
	% continuation --version 
	0.1.5
	% node -v
	v0.10.32

**Comment by BYVoid** [comment]
Thanks fixed.
